apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: teardown-flatcar-vm
  namespace: argo
spec:
  serviceAccountName: argo
  templates:
    - name: teardown-vm
      inputs:
        parameters:
          - name: vm-name
          - name: namespace
            value: "flatcar-test"
      resource:
        action: delete
        manifest: |
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{inputs.parameters.vm-name}}"
            namespace: "{{inputs.parameters.namespace}}"
