apiVersion: cdi.kubevirt.io/v1beta1
kind: CDIConfig
metadata:
  name: config
spec:
  # Allow CDI to pull from ghost's zot registry without TLS
  insecureRegistries:
    - "192.168.1.102:5000"
    - "ghost:5000"
